# Generated by Django 5.2.5 on 2025-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('sales_executive', 'Менеджер'), ('customer', 'Покупатель')], default='customer', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
