# Generated by Django 5.2.5 on 2025-08-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от')),
                ('shop_addresses', models.JSONField(blank=True, default=list, verbose_name='Адреса магазинов')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('computers', 'Компьютеры'), ('appliances', 'Бытовая техника'), ('home_garden', 'Дом и дача'), ('kids', 'Детские товары'), ('clothing', 'Одежда и обувь'), ('beauty_health', 'Красота и здоровье'), ('sports', 'Спорт'), ('construction', 'Строительство и ремонт'), ('pets', 'Товары для животных')], default='electronics', max_length=50, verbose_name='Категория')),
                ('promo_type', models.CharField(choices=[('none', 'Без промо'), ('season', 'Сезонная скидка'), ('sale', 'Акция'), ('special', 'Спецпредложение')], default='none', max_length=20, verbose_name='Тип промо')),
                ('is_featured', models.BooleanField(default=False, help_text='Отметьте, если товар должен отображаться в карусели (акции, скидки и т.д.)', verbose_name='Показывать в карусели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'permissions': [('add_product', 'Может добавить товар'), ('change_product', 'Может изменять товар'), ('delete_product', 'Может удалять товар'), ('view_product', 'Может просматривать товар')],
                'default_permissions': (),
            },
        ),
    ]
