# Generated by Django 5.2.5 on 2025-08-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manager',
            new_name='sales_executive',
        ),
    ]
